###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "John",
    "age": 43,
    "email": "john@gnail.com"
}
###
GET http://localhost:9000/api/users HTTP/1.1
###
GET http://localhost:9000/api/users/62c596cef3bcbfe4c64dde62 HTTP/1.1
###
PUT http://localhost:9000/api/users/62c596cef3bcbfe4c64dde62 HTTP/1.1
Content-Type: application/json

{
    "name": "John",
    "age": 46,
    "email": "john@gnail.com"
}
###
DELETE http://localhost:9000/api/users/62c596cef3bcbfe4c64dde62 HTTP/1.1